upstream backend {
    server backend:8000;
}

upstream frontend {
    server web:80;
}

#
# HTTP
#
server {
    listen 80;
    server_name marketlab.space www.marketlab.space;

    return 301 https://$host$request_uri;
}

#
# HTTPS
#
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name marketlab.space www.marketlab.space;

    client_max_body_size 20m;

    ssl_certificate /etc/nginx/ssl/origin.crt;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    #
    # Compression
    #
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 5;
    gzip_min_length 1024;

    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/xml
        application/rss+xml
        application/xml+rss
        application/vnd.ms-fontobject
        application/x-font-ttf
        application/font-woff
        application/font-woff2
        image/svg+xml;

    #
    # Django static
    #
    location /static/ {
        alias /api/static/;

        expires 30d;

        add_header Cache-Control 'public, immutable';

        access_log off;
    }

    #
    # Django media
    #
    location /media/ {
        alias /api/media/;

        expires 7d;

        add_header Cache-Control 'public';

        access_log off;
    }

    #
    # Django API
    #
    location /api/ {
        proxy_pass http://backend;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout 30;
        proxy_send_timeout 120;
        proxy_read_timeout 120;
    }

    #
    # Frontend
    #
    location / {
        proxy_pass http://frontend;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}